#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.parallel=true
org.gradle.logging.level=quiet
org.gradle.configureondemand=true
#org.gradle.priority=low

org.gradle.jvmargs=-Xmx8G \
  -Dfile.encoding=UTF-8 \
  -XX:+EnableDynamicAgentLoading \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+UseParallelGC \
  -XX:+AllowRedefinitionToAddDeleteMethods \
  -XX:+AllowRedefinitionToAddDeleteMethods \
  -Djava.net.preferIPv4Stack=true \
  -Djdk.instrument.traceUsage \
  -Dorg.jline.terminal.provider=jansi \
  --sun-misc-unsafe-memory-access=allow \
  --add-modules java.sql \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
  --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED \
  --add-opens=java.base/java.lang=ALL-UNNAMED \
  --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
  --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
  --add-opens=java.base/sun.misc=ALL-UNNAMED \
  --add-opens=java.base/java.io=ALL-UNNAMED \
  --add-opens=java.base/java.security=ALL-UNNAMED \
  --add-opens=java.base/java.util=ALL-UNNAMED \
  --add-opens=java.management/javax.management=ALL-UNNAMED \
  --add-opens=java.naming/javax.naming=ALL-UNNAMED \
  --add-opens=java.rmi/sun.rmi.transport=null \
  --enable-native-access=ALL-UNNAMED

mifos.projects.license.name=MPL-2.0
mifos.projects.license.link=https://spdx.org/licenses/MPL-2.0.html
mifos.projects.homepage=https://mifos.org
mifos.projects.bug.tracker=https://mifosforge.jira.com
mifos.projects.contact=https://mifos.org/about-us/contact-us
mifos.projects.inception.year=2026
mifos.projects.vendor=Mifos Initiative
mifos.projects.copyright=Copyright (c) 2026 Mifos Initiative
mifos.projects.scm.url=https://github.com/openMF/mifos-marketplace
mifos.projects.scm.connection.main=git@github.com:openMF/mifos-marketplace.git
mifos.projects.scm.connection.developer=git@github.com:openMF/mifos-marketplace.git
mifos.projects.contribute=https://github.com/openMF/mifos-marketplace/CONTRIBUTE.md
mifos.projects.documentation=https://docs.mifos.org/marketplace
mifos.projects.donation=https://mifos.org/donations
mifos.projects.faq=https://mifos.org/faq
mifos.projects.help=https://mifos.org
mifos.projects.translate=https://github.com/openMF/mifos-marketplace/TRANSLATE.md

mifos.developers.0.username=7ossam7atem1
mifos.developers.0.firstname=Hossam
mifos.developers.0.lastname=Hatem
mifos.developers.0.email=7ossam7atem1@gmail.com
mifos.developers.0.url=https://github.com/7ossam7atem1
mifos.developers.0.timezone=UTC+2
mifos.developers.0.organisation=Mifos Initiative
mifos.developers.0.organisationUrl=https://mifos.org
mifos.developers.0.gpg.public.key=

mifos.projects.0.id=marketplace
mifos.projects.0.group.id=org.mifos.marketplace
mifos.projects.0.description=Mifos Marketplace
mifos.projects.0.classifier=imperative
mifos.projects.0.storage=relational
mifos.projects.0.base.package=org.mifos.marketplace
mifos.projects.0.base.path=org/mifos/marketplace
mifos.projects.0.modules.path=modules
mifos.projects.0.homepage=https://mifos.org/marketplace
mifos.projects.0.bug.tracker=https://mifosforge.jira.com/marketplace
mifos.projects.0.contact=https://mifos.org/about-us/contact-us
mifos.projects.0.inception.year=2026
mifos.projects.0.vendor=Mifos Initiative - Marketplace
mifos.projects.0.copyright=Copyright (c) 2026 Mifos Initiative
